#!/usr/bin/env bash

set -ueo pipefail

# shellcheck source=SCRIPTDIR/../lib/cmd.bash
source "${LINTBALL_DIR:-"${HOME}/.lintball"}/lib/cmd.bash"

# only fix files which are fully staged in the git index
export LINTBALL_STAGED_ONLY="yes"

status=0
while read -r path; do
  if [ -n "$path" ] && [ -z "$(git check-ignore "$path")" ]; then
    if fix "$path"; then
      git add "$path"
    else
      status=1
    fi
  fi
done <<<"$(eval "$find_cmd")"

exit "$status"
