version: "3"
services:
  test:
    image: elijahru/lintball
    entrypoint: /lintball/scripts/docker-entrypoint.bash
    working_dir: /lintball/tools
    command: npm run test
    volumes:
      - ./bin:/lintball/bin:cached
      - ./lib:/lintball/lib:cached
      - ./scripts:/lintball/scripts:cached
      - ./test:/lintball/test:cached

  check:
    image: elijahru/lintball
    entrypoint: /lintball/scripts/docker-entrypoint.bash
    working_dir: /workspace
    command: lintball check .
    volumes:
      - ${LINTBALL_WORKSPACE:-.}:/workspace:cached
      - ./bin:/lintball/bin:cached
      - ./configs:/lintball/configs:cached
      - ./lib:/lintball/lib:cached
      - ./scripts:/lintball/scripts:cached
      - ./test:/lintball/test:cached

  fix:
    image: elijahru/lintball
    entrypoint: /lintball/scripts/docker-entrypoint.bash
    working_dir: /workspace
    command: lintball fix .
    volumes:
      - ${LINTBALL_WORKSPACE:-.}:/workspace:cached
      - ./bin:/lintball/bin:cached
      - ./configs:/lintball/configs:cached
      - ./lib:/lintball/lib:cached
      - ./scripts:/lintball/scripts:cached
      - ./test:/lintball/test:cached
