version: "3"
services:
  test:
    image: docker.io/elijahru/lintball:${LINTBALL_IMAGE_TAG:-latest}
    cache_from: docker.io/elijahru/lintball:${LINTBALL_IMAGE_TAG:-latest}
    entrypoint: /lintball/scripts/docker-entrypoint.sh
    working_dir: /lintball/tools
    command: npm run test
    volumes:
      - ./bin:/lintball/bin:cached
      - ./lib:/lintball/lib:cached
      - ./test:/lintball/test:cached

  lintball:
    image: docker.io/elijahru/lintball:${LINTBALL_IMAGE_TAG:-latest}
    cache_from: docker.io/elijahru/lintball:${LINTBALL_IMAGE_TAG:-latest}
    entrypoint: /lintball/scripts/docker-entrypoint.sh
    working_dir: /workspace
    command: lintball check .
    volumes:
      - ${LINTBALL_WORKSPACE:-.}:/workspace:cached
      - ./bin:/lintball/bin:cached
      - ./lib:/lintball/lib:cached
      - ./test:/lintball/test:cached
