#!/usr/bin/env bash

set -ueo pipefail

SCRIPTDIR="$(dirname "${BASH_SOURCE[0]}")"

# shellcheck source=SCRIPTDIR/lib/cmd.bash
source "${SCRIPTDIR}/lib/cmd.bash"

status=0
while read -r path; do
  echo "path=$path"
  if [ -n "$path" ]; then
    fix "$path" || status=1
  fi
done <<<"$(eval "$find_cmd")"

exit "$status"
