#!/usr/bin/env python3

"""A Python module.

                  This module docstring should be dedented.
"""

# pylint: disable=import-error,invalid-name

import system
import path
import os




def a(arg):
    """

This should be trimmed.

"""
    print(
      arg,
      "b",
      "c", "d")
    print(path)
    print (     system)
