# yamllint disable rule:line-length

name: Test
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  tests:
    name: bats unit tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.x"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            nim 1.4.2

      # Install packages in a cache-friendly way, uses config from cache.js
      - uses: ktmud/cached-dependencies@v1
        with:
          run: |
            set -euxo pipefail

            cache-restore npmDev
            npm --prefix="${PWD}/deps" install --include=dev
            # seems to be necessary for node >= 15
            [ -n "$(which bats)" ] || (cd deps; npm link bats)
            cache-save npmDev

            cache-restore pip
            python3 -m venv "${PWD}/deps/python-env"
            deps/python-env/bin/pip install -r deps/requirements-pip.txt
            cache-save pip

            cache-restore gem
            gem install bundler
            cache-save gem

            BUNDLE_GEMFILE="${PWD}/deps/Gemfile"
            export BUNDLE_GEMFILE

            bundle config set --local deployment 'true'
            cache-restore bundler
            bundle install
            cache-save bundler

            cache-restore brew
            brew install $(cat deps/requirements-brew.txt)
            cache-save brew

            cache-restore apt
            sudo apt-get update
            sudo apt-get install -y $(cat deps/requirements-apt.txt)
            cache-save apt

      - name: Run tests
        run: cd deps && npm run test

  lint:
    name: lint

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      # Install packages in a cache-friendly way, uses config from cache.js
      - uses: ktmud/cached-dependencies@v1
        with:
          run: |
            set -euxo pipefail

            cache-restore npm
            npm --prefix="${PWD}/deps" install
            cache-save npm

            cache-restore brew
            brew install $(cat deps/requirements-brew.txt)
            cache-save brew

      - name: Check for linter issues
        run: ./bin/lintball check

  install:
    name: install - sanity check
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Run install script
        shell: bash
        run: curl -o- https://raw.githubusercontent.com/elijahr/lintball/${GITHUB_SHA}/install.sh | bash

      - name: Verify installation
        shell: bash
        run: lintball --help
