# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation

name: Test
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  bats:
    name: bats unit tests (${{ matrix.runs-on }})
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install bash parallel

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - uses: dtolnay/rust-toolchain@nightly

      - name: Install tools
        shell: bash
        run: |
          set -euxo pipefail

          rustup +nightly component add clippy

          cd tools
          npm ci --verbose
          # seems to be necessary for node >= 15
          [ -n "$(which bats)" ] || npm link bats --verbose
          cd ..

          ./bin/lintball install-tools --all

      - name: Run tests
        run: |
          cd tools
          npm run test -- --tap

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tools
        shell: bash
        run: ./bin/lintball install-tools

      - name: Run lintball
        shell: bash
        run: ./bin/lintball check

  install-local:
    name: test local installation
    runs-on: ubuntu-latest

    steps:
      - name: Install lintball
        shell: bash
        run: npm ci "https://github.com/${GITHUB_REPOSITORY}.git#${GITHUB_SHA}"

      - name: Install tools
        shell: bash
        run: npx lintball install-tools --all

      - name: Run lintball
        shell: bash
        run: npx lintball --help

  install-global:
    name: test global installation
    runs-on: ubuntu-latest

    steps:
      - name: Install lintball
        shell: bash
        run: sudo npm ci -g "https://github.com/${GITHUB_REPOSITORY}.git#${GITHUB_SHA}"

      - name: Install tools
        shell: bash
        run: sudo lintball install-tools --all

      - name: Run lintball
        shell: bash
        run: lintball --help
